# 默认配置
server:
  port: 8066
  servlet:
    context-path: /mycrud

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:8889/springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver # 也可以
    username: root
    password: root
    initialSize: 20
    minIdle: 50
    maxActive: 500
  # 选择对应的环境配置，这里选择了 test
  profiles:
    active: prod

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: org.example.demo.bean
  mapper-locations: classpath:mappers/*.xml