# 默认配置
server:
  port: 8080
  servlet:
    context-path: /aaa

person:
  lastName: 张三
  age: 18
  boss: false
  birth: 1990/12/12
  maps: { k1: v1, k2: v2 }
  lists:
    - lisi
    - zhouliu
  dog:
    name: 二哈
    age: 5

spring:
  #数据源配置
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver # 也可以
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8889/springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    initialSize: 20
    minIdle: 50
    maxActive: 500
  # 选择对应的环境配置，这里选择了 test
  profiles:
    active: prod

---
# 开发环境
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev

---
# 测试环境
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: test

---
# 生产环境
server:
  port: 8083
  servlet:
    context-path: /aaa

spring:
  config:
    activate:
      on-profile: prod
